import Head from "next/head";
import styles from "../styles/Home.module.css";
import Slider from "../components/Slider";
import Search from "../components/Search";
import Services from "../components/Services";
import CardList from "../components/CardList";
import Footer from "../components/Footer";

const cars = [
  {
    id: 1,
    title: "McLaren GT Super",
    price: "$30",
    km: "66,500",
    gear: "Automatic",
    seat: 4,
    bag: 3,
    url: "/cars/car1.jpg",
    favorite: false,
  },
  {
    id: 2,
    title: "Porche 911 Carrer",
    price: "$60",
    km: "16,500",
    gear: "Automatic",
    seat: 2,
    bag: 3,
    url: "/cars/car2.jpg",
    favorite: true,
  },
  {
    id: 3,
    title: "Audi E-Tron",
    price: "$30",
    km: "6,500",
    gear: "Automatic",
    seat: 4,
    bag: 3,
    url: "/cars/car3.jpg",
    favorite: false,
  },
  {
    id: 4,
    title: "BMW xDrive",
    price: "$50",
    km: "26,500",
    gear: "Automatic",
    seat: 4,
    bag: 3,
    url: "/cars/car4.jpg",
    favorite: false,
  },
  {
    id: 5,
    title: "Novitec Ferrari",
    price: "$30",
    km: "56,500",
    gear: "Automatic",
    seat: 4,
    bag: 3,
    url: "/cars/car5.jpg",
    favorite: false,
  },
  {
    id: 6,
    title: "Rolls Royce Fuxia",
    price: "$90",
    km: "36,500",
    gear: "Automatic",
    seat: 4,
    bag: 2,
    url: "/cars/car6.jpg",
    favorite: false,
  },
  {
    id: 7,
    title: "BMW Alpina B4",
    price: "$60",
    km: "36,500",
    gear: "Automatic",
    seat: 4,
    bag: 3,
    url: "/cars/car7.jpg",
    favorite: false,
  },
  {
    id: 8,
    title: "Chevrolet Camaro",
    price: "$100",
    km: "26,500",
    gear: "Automatic",
    seat: 4,
    bag: 3,
    url: "/cars/car8.jpg",
    favorite: true,
  },
];

export default function Home({ cars }) {
  return (
    <div className="home_content">
      <Head>
        <title>LIMOREX AUTO RENTALS</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width,height=device-height,initial-scale=1.0"
        />
        <link rel="icon" href="/sport-car.png" />
      </Head>
      <Slider />
      <Search />
      <Services />
      <hr className={styles.home_content_hr} />
      <CardList cars={cars} />
      <Footer />
    </div>
  );
}

Home.getInitialProps = () => {
  return { cars: cars };
};
